import Foundation

/// Minimal in-app localization for the Settings screen, driven by the reader's
/// chosen `Language` (not the system locale). English strings act as the keys;
/// any language/key without a translation falls back to English.
///
/// Fully translated: English, Spanish, French, German, Italian, Portuguese,
/// Dutch, Japanese. Key labels also translated for a dozen more languages.
enum L {
    static func t(_ english: String, _ language: Language) -> String {
        if language == .english { return english }
        return table[language]?[english] ?? english
    }

    static let table: [Language: [String: String]] = [
        .spanish: [
            "Settings": "Ajustes", "Language & region": "Idioma y región", "Language": "Idioma",
            "News from": "Noticias de", "News revolves around %@, from %@.": "Las noticias giran en torno a %@, de %@.",
            "Focus on a country": "Enfocar en un país", "Country": "País", "Worldwide": "Todo el mundo",
            "Pick a country to read about it in your language.": "Elige un país para leer sobre él en tu idioma.",
            "Reading aloud": "Lectura en voz alta", "Read articles aloud": "Leer artículos en voz alta",
            "Opening an article reads it aloud.": "Al abrir un artículo se lee en voz alta.",
            "Your profile": "Tu perfil", "Age": "Edad", "Feed": "Feed", "Change age": "Cambiar edad",
            "What you can see": "Lo que puedes ver", "About": "Acerca de", "Sources": "Fuentes",
            "News is grouped by age so younger readers see suitable topics.": "Las noticias se agrupan por edad para que los más jóvenes vean temas adecuados.",
            "Your feed updates to match your age.": "Tu feed se actualiza según tu edad.",
            "Save": "Guardar", "Cancel": "Cancelar",
            "Voice": "Voz", "Preview voice": "Escuchar voz", "Automatic": "Automático",
            "Suggested for you": "Sugerencias para ti",
            "Friendly stories about science, sports, animals and space.": "Historias amigables sobre ciencia, deportes, animales y espacio.",
            "World events, technology and the environment, plus the kids' topics.": "Actualidad mundial, tecnología y medio ambiente, además de los temas infantiles.",
            "Full worldwide coverage including politics, business and crime.": "Cobertura mundial completa, incluida política, economía y sucesos.",
        ],
        .french: [
            "Settings": "Réglages", "Language & region": "Langue et région", "Language": "Langue",
            "News from": "Actualités de", "News revolves around %@, from %@.": "Les actualités tournent autour de %@, via %@.",
            "Focus on a country": "Se concentrer sur un pays", "Country": "Pays", "Worldwide": "Monde entier",
            "Pick a country to read about it in your language.": "Choisissez un pays pour le suivre dans votre langue.",
            "Reading aloud": "Lecture à voix haute", "Read articles aloud": "Lire les articles à voix haute",
            "Opening an article reads it aloud.": "L'ouverture d'un article le lit à voix haute.",
            "Your profile": "Votre profil", "Age": "Âge", "Feed": "Fil", "Change age": "Modifier l'âge",
            "What you can see": "Ce que vous pouvez voir", "About": "À propos", "Sources": "Sources",
            "News is grouped by age so younger readers see suitable topics.": "Les actualités sont classées par âge afin que les plus jeunes voient des sujets adaptés.",
            "Your feed updates to match your age.": "Votre fil s'adapte à votre âge.",
            "Save": "Enregistrer", "Cancel": "Annuler",
            "Voice": "Voix", "Preview voice": "Écouter la voix", "Automatic": "Automatique",
            "Suggested for you": "Suggestions pour vous",
            "Friendly stories about science, sports, animals and space.": "Des histoires bienveillantes sur la science, le sport, les animaux et l'espace.",
            "World events, technology and the environment, plus the kids' topics.": "Actualité mondiale, technologie et environnement, ainsi que les thèmes pour enfants.",
            "Full worldwide coverage including politics, business and crime.": "Couverture mondiale complète, y compris politique, économie et faits divers.",
        ],
        .german: [
            "Settings": "Einstellungen", "Language & region": "Sprache & Region", "Language": "Sprache",
            "News from": "Nachrichten aus", "News revolves around %@, from %@.": "Die Nachrichten drehen sich um %@, von %@.",
            "Focus on a country": "Auf ein Land fokussieren", "Country": "Land", "Worldwide": "Weltweit",
            "Pick a country to read about it in your language.": "Wähle ein Land, um in deiner Sprache darüber zu lesen.",
            "Reading aloud": "Vorlesen", "Read articles aloud": "Artikel vorlesen",
            "Opening an article reads it aloud.": "Beim Öffnen eines Artikels wird er vorgelesen.",
            "Your profile": "Dein Profil", "Age": "Alter", "Feed": "Feed", "Change age": "Alter ändern",
            "What you can see": "Was du sehen kannst", "About": "Über", "Sources": "Quellen",
            "News is grouped by age so younger readers see suitable topics.": "Nachrichten werden nach Alter gruppiert, damit jüngere Leser passende Themen sehen.",
            "Your feed updates to match your age.": "Dein Feed passt sich deinem Alter an.",
            "Save": "Speichern", "Cancel": "Abbrechen",
            "Voice": "Stimme", "Preview voice": "Stimme anhören", "Automatic": "Automatisch",
            "Suggested for you": "Für dich vorgeschlagen",
            "Friendly stories about science, sports, animals and space.": "Freundliche Geschichten über Wissenschaft, Sport, Tiere und Weltraum.",
            "World events, technology and the environment, plus the kids' topics.": "Weltgeschehen, Technik und Umwelt sowie die Kinderthemen.",
            "Full worldwide coverage including politics, business and crime.": "Vollständige weltweite Berichterstattung inkl. Politik, Wirtschaft und Kriminalität.",
        ],
        .italian: [
            "Settings": "Impostazioni", "Language & region": "Lingua e regione", "Language": "Lingua",
            "News from": "Notizie da", "News revolves around %@, from %@.": "Le notizie ruotano attorno a %@, da %@.",
            "Focus on a country": "Concentrati su un Paese", "Country": "Paese", "Worldwide": "Tutto il mondo",
            "Pick a country to read about it in your language.": "Scegli un Paese per leggerne le notizie nella tua lingua.",
            "Reading aloud": "Lettura ad alta voce", "Read articles aloud": "Leggi gli articoli ad alta voce",
            "Opening an article reads it aloud.": "Aprendo un articolo viene letto ad alta voce.",
            "Your profile": "Il tuo profilo", "Age": "Età", "Feed": "Feed", "Change age": "Cambia età",
            "What you can see": "Cosa puoi vedere", "About": "Informazioni", "Sources": "Fonti",
            "News is grouped by age so younger readers see suitable topics.": "Le notizie sono raggruppate per età così i più giovani vedono argomenti adatti.",
            "Your feed updates to match your age.": "Il tuo feed si aggiorna in base alla tua età.",
            "Save": "Salva", "Cancel": "Annulla",
            "Voice": "Voce", "Preview voice": "Ascolta la voce", "Automatic": "Automatico",
            "Suggested for you": "Consigliati per te",
            "Friendly stories about science, sports, animals and space.": "Storie adatte su scienza, sport, animali e spazio.",
            "World events, technology and the environment, plus the kids' topics.": "Attualità mondiale, tecnologia e ambiente, più i temi per bambini.",
            "Full worldwide coverage including politics, business and crime.": "Copertura mondiale completa, inclusi politica, economia e cronaca.",
        ],
        .portuguese: [
            "Settings": "Configurações", "Language & region": "Idioma e região", "Language": "Idioma",
            "News from": "Notícias de", "News revolves around %@, from %@.": "As notícias giram em torno de %@, da %@.",
            "Focus on a country": "Focar em um país", "Country": "País", "Worldwide": "Mundo todo",
            "Pick a country to read about it in your language.": "Escolha um país para ler sobre ele no seu idioma.",
            "Reading aloud": "Leitura em voz alta", "Read articles aloud": "Ler artigos em voz alta",
            "Opening an article reads it aloud.": "Ao abrir um artigo, ele é lido em voz alta.",
            "Your profile": "Seu perfil", "Age": "Idade", "Feed": "Feed", "Change age": "Alterar idade",
            "What you can see": "O que você pode ver", "About": "Sobre", "Sources": "Fontes",
            "News is grouped by age so younger readers see suitable topics.": "As notícias são agrupadas por idade para que os mais jovens vejam temas adequados.",
            "Your feed updates to match your age.": "Seu feed é atualizado conforme sua idade.",
            "Save": "Salvar", "Cancel": "Cancelar",
            "Voice": "Voz", "Preview voice": "Ouvir voz", "Automatic": "Automático",
            "Suggested for you": "Sugestões para você",
            "Friendly stories about science, sports, animals and space.": "Histórias amigáveis sobre ciência, esportes, animais e espaço.",
            "World events, technology and the environment, plus the kids' topics.": "Atualidades mundiais, tecnologia e meio ambiente, além dos temas infantis.",
            "Full worldwide coverage including politics, business and crime.": "Cobertura mundial completa, incluindo política, economia e crime.",
        ],
        .dutch: [
            "Settings": "Instellingen", "Language & region": "Taal en regio", "Language": "Taal",
            "News from": "Nieuws uit", "News revolves around %@, from %@.": "Het nieuws draait om %@, van %@.",
            "Focus on a country": "Focus op een land", "Country": "Land", "Worldwide": "Wereldwijd",
            "Pick a country to read about it in your language.": "Kies een land om er in je taal over te lezen.",
            "Reading aloud": "Voorlezen", "Read articles aloud": "Artikelen voorlezen",
            "Opening an article reads it aloud.": "Bij het openen van een artikel wordt het voorgelezen.",
            "Your profile": "Je profiel", "Age": "Leeftijd", "Feed": "Feed", "Change age": "Leeftijd wijzigen",
            "What you can see": "Wat je kunt zien", "About": "Over", "Sources": "Bronnen",
            "News is grouped by age so younger readers see suitable topics.": "Nieuws is gegroepeerd op leeftijd zodat jongere lezers passende onderwerpen zien.",
            "Your feed updates to match your age.": "Je feed past zich aan je leeftijd aan.",
            "Save": "Opslaan", "Cancel": "Annuleren",
            "Voice": "Stem", "Preview voice": "Stem beluisteren", "Automatic": "Automatisch",
            "Suggested for you": "Voorgesteld voor jou",
            "Friendly stories about science, sports, animals and space.": "Vriendelijke verhalen over wetenschap, sport, dieren en ruimte.",
            "World events, technology and the environment, plus the kids' topics.": "Wereldnieuws, technologie en milieu, plus de kinderonderwerpen.",
            "Full worldwide coverage including politics, business and crime.": "Volledige wereldwijde dekking, inclusief politiek, economie en misdaad.",
        ],
        .japanese: [
            "Settings": "設定", "Language & region": "言語と地域", "Language": "言語",
            "News from": "ニュースの提供元", "News revolves around %@, from %@.": "ニュースは%@を中心に、%@から届きます。",
            "Focus on a country": "国を絞り込む", "Country": "国", "Worldwide": "世界全体",
            "Pick a country to read about it in your language.": "国を選ぶと、その国のニュースをあなたの言語で読めます。",
            "Reading aloud": "読み上げ", "Read articles aloud": "記事を読み上げる",
            "Opening an article reads it aloud.": "記事を開くと読み上げます。",
            "Your profile": "プロフィール", "Age": "年齢", "Feed": "フィード", "Change age": "年齢を変更",
            "What you can see": "表示される内容", "About": "アプリについて", "Sources": "情報源",
            "News is grouped by age so younger readers see suitable topics.": "ニュースは年齢別に分類され、若い読者に適した話題が表示されます。",
            "Your feed updates to match your age.": "フィードは年齢に合わせて更新されます。",
            "Save": "保存", "Cancel": "キャンセル",
            "Voice": "音声", "Preview voice": "音声を再生", "Automatic": "自動",
            "Suggested for you": "あなたへのおすすめ",
            "Friendly stories about science, sports, animals and space.": "科学、スポーツ、動物、宇宙などの親しみやすい記事。",
            "World events, technology and the environment, plus the kids' topics.": "世界の出来事、テクノロジー、環境に加え、子ども向けの話題。",
            "Full worldwide coverage including politics, business and crime.": "政治、経済、事件を含む世界全体の報道。",
        ],
        .russian: labelsOnly("Настройки", "Язык и регион", "Язык", "Новости из", "Фокус на стране",
            "Страна", "Весь мир", "Чтение вслух", "Читать статьи вслух", "Ваш профиль", "Возраст",
            "Лента", "Изменить возраст", "Что вы видите", "О приложении", "Источники", "Сохранить", "Отмена"),
        .chinese: labelsOnly("设置", "语言和地区", "语言", "新闻来源", "聚焦某个国家",
            "国家", "全球", "朗读", "朗读文章", "你的资料", "年龄",
            "信息流", "修改年龄", "你能看到的内容", "关于", "来源", "保存", "取消"),
        .korean: labelsOnly("설정", "언어 및 지역", "언어", "뉴스 출처", "국가에 집중",
            "국가", "전 세계", "소리 내어 읽기", "기사 소리 내어 읽기", "내 프로필", "나이",
            "피드", "나이 변경", "볼 수 있는 내용", "정보", "출처", "저장", "취소"),
        .arabic: labelsOnly("الإعدادات", "اللغة والمنطقة", "اللغة", "الأخبار من", "التركيز على دولة",
            "الدولة", "العالم كله", "القراءة بصوت عالٍ", "قراءة المقالات بصوت عالٍ", "ملفك الشخصي", "العمر",
            "الموجز", "تغيير العمر", "ما يمكنك رؤيته", "حول", "المصادر", "حفظ", "إلغاء"),
        .hindi: labelsOnly("सेटिंग्स", "भाषा और क्षेत्र", "भाषा", "समाचार स्रोत", "किसी देश पर ध्यान दें",
            "देश", "पूरी दुनिया", "ज़ोर से पढ़ना", "लेख ज़ोर से पढ़ें", "आपकी प्रोफ़ाइल", "उम्र",
            "फ़ीड", "उम्र बदलें", "आप क्या देख सकते हैं", "परिचय", "स्रोत", "सहेजें", "रद्द करें"),
        .turkish: labelsOnly("Ayarlar", "Dil ve bölge", "Dil", "Haberlerin kaynağı", "Bir ülkeye odaklan",
            "Ülke", "Tüm dünya", "Sesli okuma", "Makaleleri sesli oku", "Profilin", "Yaş",
            "Akış", "Yaşı değiştir", "Görebilecekleriniz", "Hakkında", "Kaynaklar", "Kaydet", "İptal"),
        .indonesian: labelsOnly("Pengaturan", "Bahasa & wilayah", "Bahasa", "Berita dari", "Fokus pada negara",
            "Negara", "Seluruh dunia", "Baca dengan suara", "Bacakan artikel", "Profil Anda", "Usia",
            "Umpan", "Ubah usia", "Yang bisa Anda lihat", "Tentang", "Sumber", "Simpan", "Batal"),
        .vietnamese: labelsOnly("Cài đặt", "Ngôn ngữ & khu vực", "Ngôn ngữ", "Tin từ", "Tập trung vào một quốc gia",
            "Quốc gia", "Toàn thế giới", "Đọc to", "Đọc to bài viết", "Hồ sơ của bạn", "Tuổi",
            "Bảng tin", "Đổi tuổi", "Những gì bạn có thể xem", "Giới thiệu", "Nguồn", "Lưu", "Hủy"),
        .swedish: labelsOnly("Inställningar", "Språk och region", "Språk", "Nyheter från", "Fokusera på ett land",
            "Land", "Hela världen", "Uppläsning", "Läs upp artiklar", "Din profil", "Ålder",
            "Flöde", "Ändra ålder", "Vad du kan se", "Om", "Källor", "Spara", "Avbryt"),
        .norwegian: labelsOnly("Innstillinger", "Språk og region", "Språk", "Nyheter fra", "Fokuser på et land",
            "Land", "Hele verden", "Opplesing", "Les opp artikler", "Profilen din", "Alder",
            "Strøm", "Endre alder", "Hva du kan se", "Om", "Kilder", "Lagre", "Avbryt"),
        .danish: labelsOnly("Indstillinger", "Sprog og region", "Sprog", "Nyheder fra", "Fokusér på et land",
            "Land", "Hele verden", "Oplæsning", "Læs artikler højt", "Din profil", "Alder",
            "Feed", "Skift alder", "Hvad du kan se", "Om", "Kilder", "Gem", "Annuller"),
        .finnish: labelsOnly("Asetukset", "Kieli ja alue", "Kieli", "Uutislähde", "Keskity maahan",
            "Maa", "Koko maailma", "Ääneen lukeminen", "Lue artikkelit ääneen", "Profiilisi", "Ikä",
            "Syöte", "Vaihda ikä", "Mitä voit nähdä", "Tietoja", "Lähteet", "Tallenna", "Peruuta"),
    ]

    /// Builds a partial dictionary from the common short labels, in English-key order.
    private static func labelsOnly(
        _ settings: String, _ langRegion: String, _ language: String, _ newsFrom: String,
        _ focusCountry: String, _ country: String, _ worldwide: String, _ readingAloud: String,
        _ readAloud: String, _ profile: String, _ age: String, _ feed: String, _ changeAge: String,
        _ whatYouSee: String, _ about: String, _ sources: String, _ save: String, _ cancel: String
    ) -> [String: String] {
        [
            "Settings": settings, "Language & region": langRegion, "Language": language,
            "News from": newsFrom, "Focus on a country": focusCountry, "Country": country,
            "Worldwide": worldwide, "Reading aloud": readingAloud, "Read articles aloud": readAloud,
            "Your profile": profile, "Age": age, "Feed": feed, "Change age": changeAge,
            "What you can see": whatYouSee, "About": about, "Sources": sources,
            "Save": save, "Cancel": cancel,
        ]
    }
}
